// Default database of cars on stock for Top Car Vissenbjerg
const defaultCars = [
    {
        "id": "car-1",
        "brand": "Peugeot",
        "model": "208",
        "variant": "1,2 PureTech 100 Allure Sky 5d",
        "price": 129900,
        "year": 2020,
        "mileage": 30000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,2 (100 HK)",
        "color": "Metallak",
        "consumption": "26,2 km/l",
        "tax": "700 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Glastag",
            "Navigation"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/33e23052-10ed-44e6-bf3b-37013c28ef1d.jpeg?class=S1024X768",
        "description": "PANORAMA GLASTAG, 16\" ALUFÆLGE, NAVIGATION VIA APPEL CARPLAY, HÅNDFRI MOBIL, BLUETOOTH, ADAPTIV FARTPILOT, BAKKAMERA, SENSOR BAG, KLIMA ANLÆG, SÆDEVARME, EN BIL DER HAR DET HELE, VI TILBYDER SUPER BILLIG FINANSIERING MED ELLER UDEN UDBETALING, VI HAR NR. PLADER TIL OMG . LEV . SE MERE PÅ TOPCAR.DK, ...",
        "link": "https://www.bilbasen.dk/brugt/bil/peugeot/208/12-puretech-100-allure-sky-5d/6180204"
    },
    {
        "id": "car-2",
        "brand": "Suzuki",
        "model": "Ignis",
        "variant": "1,2 mHybrid Active 5d",
        "price": 109900,
        "year": 2020,
        "mileage": 39000,
        "fuelType": "Hybrid",
        "transmission": "Manuel",
        "engine": "1,2 (90 HK)",
        "color": "Sort",
        "consumption": "25,6 km/l",
        "tax": "700 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Hybrid",
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/7c43b7a5-9936-442d-926d-41087bc5d210.jpeg?class=S1024X768",
        "description": "MEGET VELHOLDT , 16\" ALUFÆLGE MED HELÅRSDÆK , AIRCON , APPEL CARPLAY , TÅGELYGTER , HÅNDFRI MOBIL , BLUETOOTH , EL- SPEJLE M VARME , BAKKAMERA , DAB RADIO , TAGRÆLLING , DENNE BIL KAN FINANSIERERS TIL 2.034 KR OVER 84 MDR. UDEN UDBETALING , Oplysninger Fra DMR: El-Betjente Forreste Sideruder, Centra...",
        "link": "https://www.bilbasen.dk/brugt/bil/suzuki/ignis/12-mhybrid-active-5d/6887340"
    },
    {
        "id": "car-3",
        "brand": "BMW",
        "model": "225xe",
        "variant": "1,5 Active Tourer iPerformance aut. 5d",
        "price": 169900,
        "year": 2019,
        "mileage": 72000,
        "fuelType": "Hybrid",
        "transmission": "Automatgear",
        "engine": "1,5 (224 HK)",
        "color": "Metallak",
        "consumption": "71,2 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Hybrid",
            "Automatgear"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/86b97fef-363b-4c44-9f93-b159b37f9a52.jpeg?class=S1024X768",
        "description": "NAVIGATION , 17\" ALUFÆLGE , HÅNDFRI MOBIL , BLUETOOTH , SPORTS STOLE , DEL LÆDER , P- SENSOR FOR + BAG , FULD SERVICE , UNDERVOGNSBEHANDLET I 2022 , KLIMA ANLÆG , HELÅRSDÆK , HUSK VI TILBYDER ATTRAKTIV FINANSIERING MED ELLER UDEN UDBETALING , SE MERE PÅ TOPCAR.DK , Aut.Gear/Tiptronic, 17\" Alufælge, ...",
        "link": "https://www.bilbasen.dk/brugt/bil/bmw/225xe/15-active-tourer-iperformance-aut-5d/6300060"
    },
    {
        "id": "car-4",
        "brand": "VW",
        "model": "Golf VIII",
        "variant": "1,0 TSi 110 5d",
        "price": 169900,
        "year": 2021,
        "mileage": 88000,
        "fuelType": "Benzin",
        "transmission": "Automatgear",
        "engine": "1,0 (110 HK)",
        "color": "Metallak",
        "consumption": "22,8 km/l",
        "tax": "760 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Automatgear"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/a17b28f2-9c06-42dd-b930-d6b5d05bb1f0.jpeg?class=S1024X768",
        "description": "BEMÆRK UDSTYR !!!!! , 2021 MODEL SOMMER SAMT VINTERHJUL , ADAPTIV FARTPILOT , APPEL CARPLAY , HÅNDFRI MOBIL , BLUETOOTH , SÆDEVARME , VARME I RAT , KLIMA ANLÆG , LED LYGTER FOR OG BAG , LYS OG SYN PAKKE , VINTERPAKKE , DK PAKKE , LANE ASSIST , P- SENSOR FOR OG BAG , NØGLEFRI START , EL- HÅNDBREMSE ,...",
        "link": "https://www.bilbasen.dk/brugt/bil/vw/golf-viii/10-tsi-110-5d/6873785"
    },
    {
        "id": "car-5",
        "brand": "Citroën",
        "model": "C3",
        "variant": "1,2 PureTech 83 Feel 5d",
        "price": 106900,
        "year": 2022,
        "mileage": 34000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,2 (83 HK)",
        "color": "Metallak",
        "consumption": "22,4 km/l",
        "tax": "760 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Navigation",
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/0e231ddb-8dd9-4198-88a6-b66ef77cbe69.jpeg?class=S1024X768",
        "description": "NAVIGATION VIA APPEL CAR PLAY , FARTPILOT , SÆDEVARME , KLIMA , HÅNDFRI MOBIL , BLUETOOTH , FULD SERVICE , EN EJER , 0 FEJL , DER TILBYDES ATTRAKTIV FINANSIERING , MED ELLER UDEN UDBETALING , SE MERE PÅ TOPCAR.DK , Kørecomputer, Bagagerumsdækken, Multifunktionsrat, Læderrat, Stofindtræk, Højdejust. ...",
        "link": "https://www.bilbasen.dk/brugt/bil/citron/c3/12-puretech-83-feel-5d/6618249"
    },
    {
        "id": "car-6",
        "brand": "Opel",
        "model": "Grandland X",
        "variant": "1,2 T 130 Enjoy 5d",
        "price": 139900,
        "year": 2019,
        "mileage": 67000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,2 (130 HK)",
        "color": "Metallak",
        "consumption": "18,1 km/l",
        "tax": "1630 kr. / halvårligt",
        "sold": false,
        "featured": true,
        "tags": [
            "Velholdt"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/142fe098-e34e-4ae7-8d00-d6a29f584a06.jpeg?class=S1024X768",
        "description": "AFT. TRÆK , 17\" ALUFÆLGE , VINTERHJUL MEDFØLGER , APPEL CARPLAY , AIRCON , P-SENSOR BAG , FARTPILOT , HÅNDFRI MOBIL , BLUETOOTH , HUSK VI GIVER GERNE ET FINANSIERINGS TILBUD , MED / UDEN UDBETALING , Kørecomputer, Bagagerumsdækken, Læderrat, Multifunktionsrat, Stofindtræk, Højdejust. Førersæde, Spli...",
        "link": "https://www.bilbasen.dk/brugt/bil/opel/grandland-x/12-t-130-enjoy-5d/6805794"
    },
    {
        "id": "car-7",
        "brand": "VW",
        "model": "Golf Sportsvan",
        "variant": "1,5 TSi 150 Comfortline DSG 5d",
        "price": 184900,
        "year": 2020,
        "mileage": 86000,
        "fuelType": "Benzin",
        "transmission": "Automatgear",
        "engine": "1,5 (150 HK)",
        "color": "Sølv",
        "consumption": "20,8 km/l",
        "tax": "800 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Automatgear"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/172270dc-200e-4104-9321-1fa4db6725e3.jpeg?class=S1024X768",
        "description": "EN EJERS BIL , FULD SERVICE BOG , UNDERVOGNSBEHANDLET I 2019 & 2024 , KLIMA ANLÆG 2 ZONE , ADAPTIV FARTPILOT , 16\" ALUFÆLGE , 16\" ALUFÆLGE PÅ VINTERDÆK MEDFØLGER , P- SENSOR FOR & BAG , TÅGELYGTER , SÆDEVARME , HÅNDFRI MOBIL , BLUETOOTH , APPEL CARPLAY , APP CONNECT , VINTERPAKKE , DK PAKKE , HUSKE ...",
        "link": "https://www.bilbasen.dk/brugt/bil/vw/golf-sportsvan/15-tsi-150-comfortline-dsg-5d/6810383"
    },
    {
        "id": "car-8",
        "brand": "Suzuki",
        "model": "S-Cross",
        "variant": "1,4 Boosterjet Active 5d",
        "price": 129900,
        "year": 2016,
        "mileage": 105000,
        "fuelType": "Benzin",
        "transmission": "Automatgear",
        "engine": "1,4 (140 HK)",
        "color": "Koksgrå Metallak",
        "consumption": "18,5 km/l",
        "tax": "880 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Automatgear",
            "Navigation"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/d7751a3d-d09d-477e-a351-c0e3a721f537.jpeg?class=S1024X768",
        "description": "BEMÆRK 140 HK , 17\" ALUFÆLGE SAMT 16\" ALUFÆLGE M VINTERDÆK , AFT. TRÆK , BAKKAMERA , ORG. NAVIGATION , HÅNDFRI MOBIL , BLUETOOTH , APPEL CARPLAY , TÅGELYGTER , SÆDEVARME , KLIMAANLÆG , LED LYGTER , FARTPILOT , EL-SPEJLE M VARME , EL-RUDER FOR OG BAG , Oplysninger Fra DMR: Tågelygter For., Blinklys I...",
        "link": "https://www.bilbasen.dk/brugt/bil/suzuki/s-cross/14-boosterjet-active-5d/6827244"
    },
    {
        "id": "car-9",
        "brand": "Hyundai",
        "model": "i10",
        "variant": "1,0 MPi Advanced 5d",
        "price": 89900,
        "year": 2020,
        "mileage": 71000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,0 (67 HK)",
        "color": "Metallak",
        "consumption": "26,8 km/l",
        "tax": "700 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Velholdt"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/b85fbf17-4e17-4b99-a49a-30f96d8ff762.jpeg?class=S1024X768",
        "description": "AIRCONDITION , EL-SPEJLE M VARME , HÅNDFRI MOBIL , BLUETOOTH , APPEL CARPLAY , FARTPILOT , EL- RUDER , LÆDER MULTI RAT , EN EJER , FULD SERVICE VED HYUNDAI , UNDERVOGNSBEHANDLET FRA NY , ARMLÆN , DENNE BIL KAN FINANSIERES MED ELLER UDEN UDBETALING , Oplysninger Fra DMR: 6 Airbags, Læderrat / Gearkno...",
        "link": "https://www.bilbasen.dk/brugt/bil/hyundai/i10/10-mpi-advanced-5d/6906671"
    },
    {
        "id": "car-10",
        "brand": "Hyundai",
        "model": "Kona",
        "variant": "1,0 T-GDi Trend 5d",
        "price": 129900,
        "year": 2020,
        "mileage": 87000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,0 (120 HK)",
        "color": "Metallak",
        "consumption": "20,8 km/l",
        "tax": "800 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Velholdt"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/cc787f5c-28f3-42bf-9e0c-7c7d319b7470.jpeg?class=S1024X768",
        "description": "AFT. TRÆK , 16\" ALUFÆLGE MED HELÅRSDÆK , VARME I SÆDER + VARME I RAT , FARTPILOT , KLIMA ANLÆG , TÅGELYGTER , REGNSENSOR , BAKKAMERA , HÅNDFRI MOBIL , BLUETOOTH , APPEL CARPLAY , UNDERVOGNSBEHANDLET FRA NY , FULD SERVICE , EN EJER , ///// DENNE BIL KAN FINANSIERES MED ELLER UDEN UDBETALING , Oplysni...",
        "link": "https://www.bilbasen.dk/brugt/bil/hyundai/kona/10-t-gdi-trend-5d/6873492"
    },
    {
        "id": "car-11",
        "brand": "Hyundai",
        "model": "i20",
        "variant": "1,25 Trend 5d",
        "price": 89900,
        "year": 2016,
        "mileage": 27000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,25 (84 HK)",
        "color": "Metallak",
        "consumption": "21,3 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/e76deaac-6f1d-4105-9211-f4e17358ead2.jpeg?class=S1024X768",
        "description": "BEMÆRK KM KUN 27.000 , AIRCON , FARTPILOT . SÆDEVARME , VARME I RAT , HÅNDFRI MOBIL BLUETOOTH , EL- SPEJLE / M VARME , EL- RUDER FOR&BAG , BAKSENSOR , EN BIL DER STÅR SUPER FLOT , HUSK VI TILBYDER FINANSIERING MED / UDEN UDBETALING Oplysninger Fra DMR: Bakalarm, Sædevarme For, El-Spejle M.Varme, Air...",
        "link": "https://www.bilbasen.dk/brugt/bil/hyundai/i20/125-trend-5d/6932869"
    },
    {
        "id": "car-12",
        "brand": "Ford",
        "model": "Focus",
        "variant": "1,0 SCTi 100 Titanium 5d",
        "price": 99900,
        "year": 2017,
        "mileage": 65000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,0 (100 HK)",
        "color": "Metallak",
        "consumption": "21,7 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Navigation"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/4cd4bf16-6310-4cd6-9f4a-fcaa797662a9.jpeg?class=S1024X768",
        "description": "NU 99.900 KR , SPAR 5.000 KR NAVIGATION , KLIMA , 16\" ALUFÆLGE , FARTPILOT , HÅNDFRI MOBIL , BLUETOOTH , NØGLEFRI START , FARTPILOT , TÅGELYGTER , SÆDEVARME , VINTERHJUL MEDFØLGER , VI TILBYDER FINANSIERING UDEN UDBETALING , LØBETID 96 Mdr. , 1.576 Kr HUSK VI HAR NR. PLADER PÅ LAGER , SE MERE PÅ TOP...",
        "link": "https://www.bilbasen.dk/brugt/bil/ford/focus/10-scti-100-titanium-5d/6144802"
    },
    {
        "id": "car-13",
        "brand": "Hyundai",
        "model": "i20",
        "variant": "1,0 T-GDi Essential 5d",
        "price": 139900,
        "year": 2021,
        "mileage": 49000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,0 (100 HK)",
        "color": "Metallak",
        "consumption": "23,3 km/l",
        "tax": "760 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/81c3d55e-c75f-4ebf-9d35-b64f2cd868d3.jpeg?class=S1024X768",
        "description": "HELÅRSDÆK SAMT SOMMERDÆK , APPEL CARPLAY , HÅNDFRI MOBIL , BLUETOOTH , P-SENSOR BAG , BAKKAMERA , KLIMA ANLÆG , TÅGELYGTER , VARME I RAT , SÆDEVARME , FARTPILOT , EL-RUDER FOR & BAG , REGN SENSOR , DAB + RADIO , SERVICE OK VED HYUNDAI , UNDERVOGNSBEHANDLET 2022 , EN BIL DER SKAL SES , HUSK VI TILBYD...",
        "link": "https://www.bilbasen.dk/brugt/bil/hyundai/i20/10-t-gdi-essential-5d/6743997"
    },
    {
        "id": "car-14",
        "brand": "Toyota",
        "model": "Yaris",
        "variant": "1,3 VVT-i T2 Limited 5d",
        "price": 79900,
        "year": 2016,
        "mileage": 117000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,3 (99 HK)",
        "color": "Metallak",
        "consumption": "20,4 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Velholdt"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/95b251ea-dff8-48ae-91ac-a97a516e1d53.jpeg?class=S1024X768",
        "description": "FAST TRÆK , BAKKAMERA , 15\" ALUFÆLGE , AIRCONDITION , FARTPILOT , SÆDEVARME , HÅNDFRI MOBIL , BLUETOOTH , TÅGELYGTER , FULD SERVICE BOG VED TOYTOTA , UNDERVOGNSBEHANDLET FRA NY , RIGTIG FIN BIL , DENNE BIL KAN VI TILBYDE FINANSIERING , MED ELLER UDEN UDBETALING , Kørecomputer, Bagagerumsdækken, Dobb...",
        "link": "https://www.bilbasen.dk/brugt/bil/toyota/yaris/13-vvt-i-t2-limited-5d/6906168"
    },
    {
        "id": "car-15",
        "brand": "Toyota",
        "model": "Yaris",
        "variant": "1,5 Hybrid H2 Touch CVT 5d",
        "price": 79900,
        "year": 2012,
        "mileage": 112000,
        "fuelType": "Hybrid",
        "transmission": "Automatgear",
        "engine": "1,5 (99 HK)",
        "color": "Metallak",
        "consumption": "28,6 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Hybrid",
            "Automatgear"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/e4727a73-c0e4-4eb7-910a-2834ca8dcfe9.jpeg?class=S1024X768",
        "description": "NAVIGATION , HÅNDFRI MOBIL , BLUETOOTH , BAKKAMERA , 2 ZONET KLIMAANLÆG , FARTPILOT , SÆDEVARME , EL-SPEJLE M. VARME , EN EJER , STÅR PÅ HELÅRSDÆK , FULD SERVICE BOG VED TOYOTA , HUSK AT FÅ ET TILBUD PÅ FINANSIERING MED ELLER UDEN UDBETALING , Oplysninger Fra DMR: Rat Højdejusterbart, Servostyring, ...",
        "link": "https://www.bilbasen.dk/brugt/bil/toyota/yaris/15-hybrid-h2-touch-cvt-5d/6907111"
    },
    {
        "id": "car-16",
        "brand": "Toyota",
        "model": "Yaris",
        "variant": "1,5 VVT-iE T2 Premium 5d",
        "price": 109900,
        "year": 2018,
        "mileage": 85000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,5 (111 HK)",
        "color": "Metallak",
        "consumption": "20,8 km/l",
        "tax": "800 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Velholdt"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/af0e6360-7a83-405d-91ce-c8dc9b99be8b.jpeg?class=S1024X768",
        "description": "FAST TRÆK , EN EJER , FULD SERVICE VED TOYOTA , UNDERVOGNSBEHANDLET FRA NY , VINTERHJUL MEDFØLGER , 15\" ALUFÆLGE , BAKKAMERA , FARTPILOT , KLIMAANLÆG , SÆDEVARME , DENNE BIL KAN FINANSIERES UDEN UDBETALING , Oplysninger Fra DMR: Dørhåndtag, Lakerede, Digitalinstrumentering (3-Dimensional), 1G2 Plati...",
        "link": "https://www.bilbasen.dk/brugt/bil/toyota/yaris/15-vvt-ie-t2-premium-5d/6887853"
    },
    {
        "id": "car-17",
        "brand": "Mazda",
        "model": "2",
        "variant": "1,5 SkyActiv-G 90 Sky 5d",
        "price": 139900,
        "year": 2021,
        "mileage": 24000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,5 (90 HK)",
        "color": "Metallak",
        "consumption": "25,2 km/l",
        "tax": "700 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Navigation",
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/bf2c308f-8c0f-4651-bbbd-76799fd47e20.jpeg?class=S1024X768",
        "description": "HÅNDFRI MOBIL , BLUETOOTH , NAVIGATION VIA APPEL CARPLY , 15\" ALUFÆLGE , FARTPILOT , SÆDEVARME , EL- SPEJLE M VARME , EL-RUDER FOR OG BAG , AIRCON , P-SENSOR BAG , DAB + RADIO , VI TILBYDER GERNE FINASIERING MED ELLER UDEN UDBETALING , SE MERE PÅ TOPCAR.DK , Oplysninger Fra DMR: El-Ruder For Og Bag,...",
        "link": "https://www.bilbasen.dk/brugt/bil/mazda/2/15-skyactiv-g-90-sky-5d/6641145"
    },
    {
        "id": "car-18",
        "brand": "Renault",
        "model": "Captur",
        "variant": "1,6 E-Tech Intens 5d",
        "price": 144900,
        "year": 2020,
        "mileage": 42000,
        "fuelType": "Hybrid",
        "transmission": "Automatgear",
        "engine": "1,6 (160 HK)",
        "color": "Metallak",
        "consumption": "40,3 km/l",
        "tax": "540 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Hybrid",
            "Automatgear"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/a58cc717-4177-40ea-a5c7-d345f5fcbbfd.jpeg?class=S1024X768",
        "description": "17\" ALUFÆLGE , NÆSTEN NYE VINTERHJUL MEDFØLGER , UNDERVOGNSBEHANDLET I 2024 , BAKKAMERA , P- SENSOR FOR OG BAG , NAVIGATION , HÅNDFRI MOBIL , BLUETOOTH , VARME I RAT , SÆDEVARME , VI TILBYDER FINANSIERING MED ELLER UDEN UDBETALIG VED SANTANDER , EN BIL DER STÅR SOM NY , Oplysninger Fra DMR: Renault ...",
        "link": "https://www.bilbasen.dk/brugt/bil/renault/captur/16-e-tech-intens-5d/6801480"
    },
    {
        "id": "car-19",
        "brand": "Toyota",
        "model": "Aygo",
        "variant": "1,0 VVT-i x-change 5d",
        "price": 79900,
        "year": 2015,
        "mileage": 19000,
        "fuelType": "Benzin",
        "transmission": "Manuel",
        "engine": "1,0 (69 HK)",
        "color": "Metallak",
        "consumption": "26,3 km/l",
        "tax": "460 kr. / halvårligt",
        "sold": false,
        "featured": false,
        "tags": [
            "Navigation",
            "Lavt km-tal"
        ],
        "image": "https://billeder.bilbasen.dk/bilinfo/b483afb6-72a5-4ed4-af19-cf2985307f01.jpeg?class=S1024X768",
        "description": "BEMÆRK KUN 19.000 KM , EN EJER , FULD SERVICE , UNDERVOGNSBEHANDLET , 2015 & 2021 , NAVIGATION , BAKKAMERA , HÅNDFRI MOBIL , BLUETOOTH , AIRCON , EN BIL DER STÅR SOM NY , VI KAN TILBYDE FINANSIERING MED / UDEN UDBETALING , Kørecomputer, Bagagerumsdækken, Multifunktionsrat, Læderrat, Stofindtræk, Høj...",
        "link": "https://www.bilbasen.dk/brugt/bil/toyota/aygo/10-vvt-i-x-change-5d/6919134"
    }
];

// Export to window object for browser access
window.defaultCars = defaultCars;
